title: Testing gh pages
author: nikoskou
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Not sure what this page is about yet. It might not exist for long...
  It might change completely, or it might stay as is with a couple of
  changes here and there.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
